import React from 'react'
import { FloatingParticles } from '@/components/magicui/floating-particles'
import SiteNav from '@/components/SiteNav'

export default function TermsPage() {
  return (
    <div className="relative min-h-screen bg-background text-foreground overflow-x-hidden">
      <FloatingParticles count={30} />
      <div className="fixed top-0 left-1/2 -translate-x-1/2 w-[900px] h-[500px] pointer-events-none z-0"
        style={{ background: 'radial-gradient(ellipse 60% 50% at 50% 0%, rgba(120,80,255,0.18) 0%, rgba(0,200,255,0.08) 60%, transparent 100%)' }} />
      <SiteNav />
      <main className="relative z-10 max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-12">Last updated: June 2, 2026</p>

        <div className="space-y-10 text-white/70 text-sm leading-relaxed">
          <section>
            <h2 className="text-white font-semibold text-lg mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using GGLoadout (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">2. Description of Service</h2>
            <p>GGLoadout is an AI-powered tool that generates store page copy for video games across platforms including Steam, itch.io, App Store, and Google Play. The Service is provided on a subscription basis.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">3. Account Registration</h2>
            <p>You must sign in with a valid Google account to use the Service. You are responsible for maintaining the security of your account. GGLoadout is not liable for any loss resulting from unauthorised use of your account.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">4. Free and Pro Plans</h2>
            <p>The Service offers a Free plan (3 generations per day) and a Pro plan ($9 USD per month, up to 50 generations per day). Plan limits are enforced on a rolling 24-hour basis. GGLoadout reserves the right to modify plan limits with reasonable notice.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">5. Payments and Billing</h2>
            <p>Payments for the Pro plan are processed by Paddle.com, our authorised reseller and Merchant of Record. By subscribing, you agree to Paddle&apos;s terms of service and authorise recurring monthly charges. You may cancel your subscription at any time; access continues until the end of your billing period.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">6. AI-Generated Content</h2>
            <p>The copy generated by GGLoadout is produced by AI. You are solely responsible for reviewing, editing, and ensuring the accuracy and compliance of any content before publishing it to any platform. GGLoadout does not guarantee that generated content will meet any platform&apos;s specific requirements.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">7. Intellectual Property</h2>
            <p>You retain ownership of any game information you provide. The AI-generated output is provided to you for your use. GGLoadout retains ownership of the Service, including its software, design, and branding.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">8. Prohibited Use</h2>
            <p>You agree not to use the Service to generate content that is illegal, misleading, or violates any third-party rights. Automated or bulk use of the Service beyond stated plan limits is prohibited.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">9. Disclaimer of Warranties</h2>
            <p>The Service is provided &quot;as is&quot; without warranties of any kind. GGLoadout does not warrant that the Service will be error-free, uninterrupted, or that results will be accurate for any particular purpose.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">10. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, GGLoadout shall not be liable for any indirect, incidental, or consequential damages arising from use of the Service.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">11. Changes to Terms</h2>
            <p>We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">12. Contact</h2>
            <p>For questions about these terms, contact us at <a href="mailto:hello@ggloadout.com" className="text-white/60 hover:text-white underline">hello@ggloadout.com</a>.</p>
          </section>
        </div>
      </main>
      <footer className="relative z-10 border-t border-white/[0.07] py-8 mt-10">
        <div className="max-w-6xl mx-auto px-6 flex items-center justify-between">
          <span className="text-white/40 text-sm">© 2026 GGLoadout</span>
          <div className="flex gap-6 text-sm text-white/40">
            <a href="/privacy" className="hover:text-white/70">Privacy Policy</a>
            <a href="/refund" className="hover:text-white/70">Refund Policy</a>
          </div>
        </div>
      </footer>
    </div>
  )
}
